export default {
  login: 'user/login',
  register: 'user/register',
  confirmUser: 'user/confirm',
  resetPassword: 'user/resetPassword',
  setNewPassword: 'user/setNewPassword',
  localizations: 'localization',
  postsFromLocalizations: 'post/localizations/uids',
  user: 'user',
  postLike: 'like/post',
  comments: 'comment',
  commentLike: 'like/comment',
  post: 'post',
  postToLocalization: 'post/localization',
  categories: 'category',
  notifications: 'notification',
  groupedLocalizations: 'localization/groupedByPlace/categories',
  getPostByComment: 'comment/withPostData',
  setNotificationAsSeen: 'notification/seen',
};
